name: Make on Ubuntu

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Ubuntu with make
        run: |
         curl https://raw.githubusercontent.com/SeigneurLefou/Marvin-the-Paranoid-Assistant/refs/heads/main/install.sh | sh
         export PATH=$PATH:$HOME/.local/bin/
